version: "3"

services:
    app:
        container_name: thc-sp
        image: thc-sp
        build: .
        ports:
            -   "8080:8080"
        depends_on:
            -   db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=root
            
    db:
        container_name: db
        image: 'postgres:13.1-alpine'
        ports:
            -   "5433:5432"
        environment:
            -   POSTGRES_USER=postgres
            -   POSTGRES_PASSWORD=root
            -   POSTGRES_DB=postgres